### ISSUE TITLE
How to obtain incidence angle from source to OE 

### ISSUE THREAD

**Issue by NolannR** [kklmn/xrt#102]
Hi,

The microscope I try simulate has two mirrors, and I would like to obtain the angle of arrival from the source to the first mirror, and the angle of arrival from the first mirror to the second mirror. How can I do so ?

Ideally, if I can get all the (theta_1, theta_2) couples for each pixel on the detector, it'd be perfect.

Thank you in advance for your answer,

**Comment by kklmn** [comment]
Hi,

Each beam has arrays 'a', 'b' and 'c' that contain directional cosines per ray.

If you want to use the xrt's histogramming functions, you can visualize `x'` and `z'` as any of the plot axes (x, y or c) or you can visualize `theta` or even any function of beam arrays, see [here](https://xrt.readthedocs.io/plots.html#xrt.plotter.XYCAxis).
See the last picture of [this example](https://xrt.readthedocs.io/gallery2.html#polycapillary), where the color axis is `x'`.

If you want to analyze the ray directions yourself, make a scalar product of these abc vectors of a local beam with a local normal (otherwise of a global beam with a global normal). For an optical element the local normal is [0, 0, 1] and for a screen it is [0, -1, 0]. You can do this in your `run_process()` function.
