### ISSUE TITLE
optic surface normal vector and intersection point with incident ray

### ISSUE THREAD

**Issue by leahwang1962** [kklmn/xrt#114]
Hi, in  XRTGlow, is it possible to display  the  intersection point coordinate value(local or global) of  incident ray with optic surface, and the optic surface normal vector at this point?  Let's assume only tracing one ray, passing through source center and optic center.
Thanks.

**Comment by yxrmz** [comment]
Hi, it's not possible now, sorry. I would just save a screenshot and add overlay text in a photo editor.
I can hardly imagine the usability of this feature - we normally work with hundreds of thousands of rays, no way to annotate all of them or even select which ones you want to annotate. What I can try to implement is a tooltip-kind text and instant surface normal when you move your mouse over an intersection point, but might end up in annoying pixel-hunting.

**Comment by leahwang1962** [comment]
Totally understandable. The reason I asked for this is I found some reflected rays behaving strangely, and I planed to manually calculate the reflected ray at these points given the intersection coordinates and surface normal vectors to figure out what is going wrong. The incident ray from point source hit vertical mirror first and reflected to hit the horizontal mirror. However as shown in the attached, the incident ray on the first mirror looks not reflected following the surface reflection rule(red color for incident ray, blue color for reflected)  . Same thing happens when ray hit the second mirror surface. Can you help me for this confusion. Thanks a lot.
![RefletedRayByVerticaleMirror](https://user-images.githubusercontent.com/99756010/173413669-fad53827-557e-4286-aaec-982e125c70b0.jpg)
[CMF11-29Cu15.zip](https://github.com/kklmn/xrt/files/8893337/CMF11-29Cu15.zip)

?

**Comment by kklmn** [comment]
Hi,
Since you don't set surface limits, although you asked about it in #104, rays may find an imaginary second reflection point at the back continuation of the reflected ray towards the second mirror that is _behind_ the surface of the first mirror. In my view, your definition of such intersecting mirror surfaces is not legitimate. Anyway, to cope with such cases, I've added an extra check that the propagation path is always non-negative.
Please try it from the present GH version.
