### ISSUE TITLE
Beam missing in xrtGlow

### ISSUE THREAD

**Issue by y19880621** [kklmn/xrt#13]
![bug](https://user-images.githubusercontent.com/18696534/34154677-525088b0-e4f1-11e7-8188-0af4005da089.png)

Above image shows my testing beamline with undulator source and KB mirror. As you can see, the beam lost before the first mirror. However, the footprints of the beam are correct as well as the final outputs. The xml file was attached below. Please change the file type to .xml, because the xml file is not supported.

[testBeamline.txt](https://github.com/kklmn/xrt/files/1571454/testBeamline.txt)

**Comment by yxrmz** [comment]
Hi,

The beam is not visible, because the propagation method assigned to the mirrors is "multiple_reflect" (should be "reflect"). It could happen due to the bug that is already fixed, most probably, the layout was created in older version of the code.
To correct this, first make sure you are using the most recent version of xrt, then you can manually replace the method in xrtQook layout right-clicking on the method and selecting the "Remove multiple_reflect()" and afterwards right-clicking again on the optical element and selecting "Add method -> reflect()" in context menu. Make sure to select proper beams in the input parameters of new method. Repeat the procedure for the second mirror.
Just in case, I attach the corrected file to this message.
Thanks for your feedback and sorry for inconvenience,
[testBeamline_reflect.txt](https://github.com/kklmn/xrt/files/1571846/testBeamline_reflect.txt)

**Comment by y19880621** [comment]
Thanks a lot.
