### ISSUE TITLE
Example for distorted surfaces

### ISSUE THREAD

**Issue by brttmnl** [kklmn/xrt#157]
Hi, 
I had a look at your example for the implementation of distorted surfaces and I suspect that your interpolation of the surface error is not working correctly. In the init function of ToroidMirrorDistorted, you interpolate warpZ, warpA and warpB using dimage.spline_filter, which does not takt the x, y coordinates of the data points into account, i.e. it assumes the array index as coordinate. 
    self.warpSplineZ = ndimage.spline_filter(self.warpZ)
    self.warpSplineA = ndimage.spline_filter(self.warpA)
    self.warpSplineB = ndimage.spline_filter(self.warpB)
In the functions local_z_distorted and local_n_distorted, you map the splines from above (wrong grid) on new coordinates. 
    z = ndimage.map_coordinates(self.warpSplineZ, coords, prefilter=True)
    a = ndimage.map_coordinates(self.warpSplineA, coords, prefilter=True)
    b = ndimage.map_coordinates(self.warpSplineB, coords, prefilter=True)

Instead the following code gives in my opinion correct results. 
     self.warpSplineZ = interpolate.RegularGridInterpolator((self.warpX, self.warpY), self.warpZ)
     self.warpSplineA = interpolate.RegularGridInterpolator((self.warpX, self.warpY), self.warpA)
     self.warpSplineB = interpolate.RegularGridInterpolator((self.warpX, self.warpY), self.warpB)
     z = self.warpSplineZ(coords)
     a = self.warpSplineA(coords)
     b = self.warpSplineB(coords)

Could you please comment?
Thanks

**Comment by kklmn** [comment]
Hi,

If you haven't done so yet, please uncomment `see_the_bump()` at the very end of the script and comment `main()` out. You will see the surface and some random samples that are put on the surface. Their color is given by z coordinate and it matches the surface color around them, so that most of these spots you don't even see. The gradient vectors also always directed from high to low values. So the interpolation does look correct.

It is another issue that you probably don't understand the implementation, but to call it incorrect, you should provide an evidence. What is it?

**Comment by brttmnl** [comment]
Ah ok, you do the transformation for local coordinates to array index using 
coords = np.array(  [(x-self.limPhysX[0]) / (self.limPhysX[1]-self.limPhysX[0]) * (self.warpNX-1),
             (y-self.limPhysY[0]) /  (self.limPhysY[1]-self.limPhysY[0]) * (self.warpNY-1)])
Then it fits. 

I implemented a parabolic mirror with distortion, which then needed different coordinate transformation and the usage of RegularGridInterpolator was more straight forward. 
Thanks
