### ISSUE TITLE
OpenGL 3.1.7 but GLUT is not found

### ISSUE THREAD

**Issue by Z-zhq** [kklmn/xrt#196]
I don't have the red and blue glasses logo on my software, only the pattern circled in red in the picture below, and the software flashes back after clicking on it and running it for a while.
The message bar on the right says glut not found, I tried reinstalling opengl but to no avail.
Please help me! I have spent a long time on this.
<img width="194" alt="屏幕截图 2024-08-28 212329" src="https://github.com/user-attachments/assets/d419136c-9193-4283-b148-8e712739ebb3">
<img width="328" alt="屏幕截图 2024-08-28 212352" src="https://github.com/user-attachments/assets/55ffa326-ee9b-44d0-ba20-ada2eb55e7df">

**Comment by yxrmz** [comment]
Indeed, recent pyopengl wheels don't include freeglut dlls. If you really need python 3.8, one possible solution could be downloading Winpython64-3.8.7.0.exe from https://github.com/winpython/winpython/releases/tag/3.0.202011219 and extracting it. freeglut dlls would be there right from the start. you might need to "pip install sphinxcontrib-jquery" in order to run xrtQook.

**Comment by Z-zhq** [comment]
If I want to continue using Anaconda, can I change to a lower version of python to solve this problem?

**Comment by yxrmz** [comment]
I don't think simple downgrade would work. Try downloading and extracting winpython, then copying the DLLS folder to your conda environment and renaming freeglut dll files, see my comment above.

**Comment by Z-zhq** [comment]
Thank you！！！！ following your method, I solved the problem.
