### ISSUE TITLE
Model of the  distortion of the DCM

### ISSUE THREAD

**Issue by goxrt** [kklmn/xrt#26]
The distortion of the DCM will cause the change of the resolution and flux of the transimitted light. I wonder if the XRT can perform this analysis now. thanks

**Comment by kklmn** [comment]
Yes, xrt can do ray tracing with distorted surfaces. An example for mirrors is [here](https://xrt.readthedocs.io/gallery3.html#defocusing-by-a-distorted-mirror).

So far, we don't have Takagi-Taupin diffraction from distorted Bragg crystals. Roman has unofficially (without tests and documentation) implemented it for Laue. Note that none of other ray tracing or wave propagation tools has it.

So we can't provide beam degradation due to strain in the 1st crystals but geometrical factors are all there. See an example [here](https://xrt.readthedocs.io/gallery2.html#bending-of-collimating-mirror).
