### ISSUE TITLE
problem relates to the unit of the intensity

### ISSUE THREAD

**Issue by goxrt** [kklmn/xrt#27]
Hi, I am using the following code to save plot, and analyze the intensity profile, refering to the example. I wonder if I save the data using "Ixy = plot.total2D", what kind of the unit is used? I tried to compute the total flux from the data, but got wrong reslut, however, the saved picture displayed right value for flux. Thanks.

    for ic, dq in enumerate(dFocus):         
        plot = xrtp.XYCPlot(
            'beamFSMExp_{0:02d}'.format(ic), (1,), aspect='auto',
            xaxis=xrtp.XYCAxis(r'$x$', u'µm', bins=xbins, ppb=xppb),
            yaxis=xrtp.XYCAxis(r'$z$', u'µm', bins=zbins, ppb=zppb),
            fluxKind='s', title='{0}-Is_4s{1:02d}'.format(prefix,ic))
        plot.xaxis.limits = [imageExtent[0], imageExtent[1]]
        plot.yaxis.limits = [imageExtent[2], imageExtent[3]]
        plot.textPanel = plot.fig.text(
            0.88, 0.8, u'f{0:+.0f} mm'.format(dq),
            transform=plot.fig.transFigure, size=12, color='r', ha='center')
        plots.append(plot)

**Comment by kklmn** [comment]
Hi,

> I wonder if I save the data using "Ixy = plot.total2D", what kind of the unit is used?

This is a Monte Carlo sum. It converts to a physical value after multiplication by the volume of the sampled physical space and normalization to the number of samples. The actual formula is in xrt/plotter/XYCPlot._get_flux(). You can apply it to plot.total2D instead of intensity and don't forget about dx*dz.

A simpler way is probably to record plot.flux or plot.power (depending on what you want) and use it as a normalization constant for your plot.total2D that you normalize to 1 beforehand.
