### ISSUE TITLE
how to calculate the flux/s vs. Energy quantitatively

### ISSUE THREAD

**Issue by angelicacecilia** [kklmn/xrt#53]
Good morning.
I successfully propagated the beam through a DCM and through a DMM by using  the examples you provide on your website.
I know how to extract the data from the pickle file that corresponds to the picture below.
How can I quantify the flux (ph/s) vs. energy?

![bm__DMMbeamGlobal01-1](https://user-images.githubusercontent.com/46441731/73249008-5093be80-41b4-11ea-8e9b-f33ad9a4dfc2.png)
Thank you for the help.
Angelica

**Comment by kklmn** [comment]
A typical way to extract ray distributions is described [here](https://xrt.readthedocs.io/using.html#saving-the-results), and an example can be found in 
`examples/withRaycing/01_SynchrotronSources/synchrotronSources.py`. In that example, we pickle some values and arrays to be used elsewhere but you can directly do plotting in the function `afterScript`.

For the energy distribution, you need plot.caxis.binEdges and plot.caxis.total1D. The sum under the curve is the number of good rays within the specified energy limits. If you want it in ph/s, normalize it to plot.flux.

It is also possible to extract some values and arrays from plot pickles if you store them. Because pickling requires serialization, a plot pickle is not the same as its corresponding plot itself. The data structure there is different. From a plot pickle you need to extract `ebinEdges`, `etotal1D` and flux is calculated as 
```flux = float(intensity) / nRaysAll * nRaysSeededI / nRaysSeeded```,
where all these variables are present in the pickle.

In the GitHub version, I've now included flux into plot pickles to facilitate its possible future usage.
