### ISSUE TITLE
[Plans] Use external crystal diffraction profile

### ISSUE THREAD

**Issue by maurov** [kklmn/xrt#7]
Hello,

This is not a feature request, just for a better understanding of your future plans. I see that you will include TT theory for bent crystals:

> dynamical theory of x-ray diffraction for bent crystals – TT theory

This is a very good idea. If possible, I would suggest to let the user have the possibility to input the crystal reflectivity as an array that could be in the form (\DeltaTheta, Reflectivity_sigma, Reflectivity_pi). Then the ray tracer engine would simply rescale each ray intensity to the reflectivity.

In fact, one could obtain the diffraction profile using, for example,

- [CRYSTAL](https://github.com/srio/CRYSTAL):  multilamellar method works nicely for the perpendicular strain field;
- [pytakagitaupin](https://github.com/aripekka/pytakagitaupin):  1D Takagi-Taupin for the vertical strain field, plus analytical for the radial one... still in early stage of development.

Thanks for your comments,
Mauro

**Comment by yxrmz** [comment]
Hi,
In fact, we already have a working module that calculates the TT-theory diffraction profiles in 2D by direct integration. The problem is that each input _ray_ gives you two divergent _beams_ in the output, so we are now trying to find the best way to keep the resulting amount of data and computational time within  reasonable limits while preserving the physical accuracy. Hope it'll be there in the next major release.
Regards,
Roman
